7_module__1_2_3_task
js-tasks-ru/jsbasic-20231109_green-voodoo pull request #10
Opened 2023-12-09 19:25 UTC by ProskurinR

2023-12-09 19:26 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-12-10 10:15 UTC, SinimaWath requested changes

2023-12-10 10:15 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    let onRibbonScrollClick = (e) => {
Функция в методе, выглядит немного странно:
- На каждый вызов функции initScrollRibbonMenu, будет создаваться функция onRibbonScrollClick.
- Усложняется чтение метода.

Вынеси `onRibbonScrollClick`, `onRibbonScroll `, в отдельные методы класса

2023-12-10 10:15 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    });
Этот обработчик события стоит вынести в отдельный метод так же, к примеру: `onRibbonSelect`

2023-12-10 10:15 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    };
Давай также вынесем в отдельный метод функцию keydownListener

2023-12-10 19:55 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-12-14 15:07 UTC, SinimaWath approved these changes

2023-12-14 15:08 UTC, merged