2 task
js-tasks-ru/jsbasic-20231109_green-voodoo pull request #2
Opened 2023-11-13 20:11 UTC by ProskurinR

2023-11-13 20:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-14 13:49 UTC, SinimaWath requested changes

2023-11-14 13:49 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  }
Всегда стоит избавляться от большой вложенности if:

Здесь можно почитать:
https://refactoring.guru/ru/replace-nested-conditional-with-guard-clauses

```
if (...) {
  console.log("Не натуральное число!");
  return;
}

if (....) {
  return 1;
}

let f = 1;
for (i = 2; i <= n; i++) {
  f = f * i;
}
return f;

```

2023-11-14 16:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-11-15 12:38 UTC, SinimaWath approved these changes

2023-11-15 12:38 UTC, merged